[[plugins]]
  package = "./plugins/indexnow"

[[plugins]]
  package = "./plugins/sitemap-lastmod"

[[headers]]
  for = "/rss.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"  